### ISSUE TITLE
Discussion regarding PAKE draft

### ISSUE THREAD

**Issue by BjoernMHaase** [chris-wood/draft-bmw-tls-pake13#3]
>Hi Chris, 
>
>thank you for again starting an effort for having PAKE integrated within TLS. I appreciate that.
>
>Hi Laura and Samir,
>
>with this mail I’d like to establish the contact to you and offer support with getting things further here.
>
>
>I have just had a very first look at your draft when sitting in some meetings in IETF121. I am having the following preliminary feedback:
>
>- I think that we will have to clarify on what client and server are to have included in their respective messages. I see the issue with >your draft that while the client will be able to include its client identity it might not be having a server identity value available when >starting the protocol. I.e. the client will not be able in practice to provide the structure that you currently specify:
>
>  struct {
>       NamedPAKE   named_pake;
>       opaque      client_identity<0..2^16-1>;
>       opaque      server_identity<0..2^16-1>;
>       opaque      pake_message<1..2^16-1>;
>   } PAKEShare;
>
>Instead I see the need that the mechanism is as follows: The client transmits a client identity field which *may* be empty. The server >includes a server identity field which also *may* be empty.
 
This is exactly what the draft specifies: the client and server identities are optional values on the wire. If they are present for the application, they are included, otherwise they are not. 

>Similarly to the certificate chain validation in a certificate-based authentication protocol we would be having application hooks on >both sides which get the respective remote identity fields and accept or reject a connection request. Probably it would be helpful to >integrate an image on how the TLS core component interfaces with a PAKE software module outside of the TLS core.
> 
This is also specified in the draft, in that the server chooses its password registration record based on the ClientHello PAKE information. If a registration record exists, it attempts to use it for authentication. Otherwise, it does not. 

>- We should be clarifying what the PAKE algorithm specifier named_pake would be including. For symmetric PAKEs there might be >the option to have named_pake specifying the algorithm family (e.g. CPace or SPAKE2) and have a separate specification of the >cipher suite (e.g. group) to be used. I think that for augemented PAKE we will have to make the named_pake ID specify both, the >protocol-type and the cipher suite set used for running the PAKE protocol. This will be necessary because the actual password >verifiers stored by the server will depend not only on the protocol type but also on the cipher suites.

>My suggestion would be to clarify this property in the draft and to make the named_pake number bundle together both, cipher suite >and protocol type together also for balanced PAKE.
 
This is already specified. The named_pake fully specifies the protocol, e.g., for SPAKE2PLUS_V1 fully specifies the group, hash function, KDF, and MAC algorithms to be used. It is expected that other named_pake values do the same. 

>…. 
>
>As a rough idea which will become relevant when drawing the interface image with the message flow between the PAKE module at >the client and at the server and the TLS core will be how to deal with the explicit key confirmation messages. In CPace we have made >a lot of effort for neat integration into TLS by explicitly keeping the key confirmation rounds separate from the PAKE protocol (and >leave it to TLS in the final two messages). This will not be the case for other PAKE constructions.
 
Indeed, not every PAKE will be as easy to integrate as CPace or SPAKE2+, but we can cross that bridge when the time comes. If, for example, a PAKE protocol requires its own key confirmation (and cannot use the TLS Finished messages), then that named_pake would have to add a round trip to TLS. While this is undesirable, it’s also not a dealbreaker.
 
Best,
Chris

>…
>
>Yours,
>
>Björn,

P.S.: I hope that you will be accepting such prelimary feedback. Please tell me if you happen to feel spammed with preliminary thoughts like the ones above which have not be thought through to all details and consequences yet. In this case I will try to give you a more comprehensive feedback and not rough ideas as above in the future. 
Mit freundlichen Grüßen | Best Regards 
Dr. Björn Haase

**Comment by BjoernMHaase** [comment]
Chris, I think that we should probably be having an image where we detail what interface we are
about to specify. I fear that otherwise we might be having difficulties regarding the abstraction layer

IMO we should be talking about the interface between a component that I’d be calling “TLS core”
and components that I’d be calling “PAKE adapter”.


```
    Client
    -----------------------  ---------------------|
     Application layer      |                     |   
                            |  Client-side        |
    Password           -->  |  TLS PAKE adapter   |
    Client MD          -->  |                     |
                            |  PAKE MSG 1+2  ->-- |
    Server MD          <--  |  PAKE RSP     -<- | |   
    session ID         <--  |  SK        ->-| | | |     
                            |               | | | |     
                             --------- ===========
    IP address + port  -->  |         |           |
                            |   TCP   |    TLS    |
           downlink <--     |         |   core    |
           uplink    -->    |         |           |
    -----------------------  ---------  ---------


    Server
    -----------------------  ---------------------|
     Application layer      |                     |   
                            |  Server-side        |
    Password/Verifier  -->  |  TLS PAKE adapter   |
    Server MD          -->  |                     |
                            |  PAKE MSG 1+2  -<-- |
    Client MD          <--  |  PAKE RSP     ->- | |
    session ID         <--  |  SK        ->-| | | |
                            |               | | | |
                             --------- ===========
    IP address + port  <--  |         |           |
                            |   TCP   |    TLS    |
           downlink  -->    |         |   core    |
           uplink    <--    |         |           |
    -----------------------  ---------  ---------


```I.e. even if I believe that we should have the PAKE Adapter code be a part
of the TLS library code, I think that for the purpose of software interfaces
in the code and for the purpose of the specification we should consider
that the TLS library will have an adapter and a core component on both sides.

In the scope of the draft I suggest, that one should be specifying the interface that I highlighted
with double lines “======” .

IMO we should be specifying what should be done in the TLS core part
and what has to be provided by the PAKE adapters on both sides and in which
sequence.

We then would be having a separate block specifying how the PAKE adapter
blocks shall behave for each of the protocols.

Saying this, at the ======= interface level we should probably not specify
on the actual contents within the PAKE message and response semantics
as this might vary with the actual PAKE protocol in some details.

On the interface to the application layer I would distinguish between the concept
of client metadata and server metadata and actual data fields within the PAKE
messages.

2.) 

I also think that we should be preparing the option of supplying an interface
between the TLS core parts and the TLS PAKE adapter parts for giving
the TLS core component access to a private/public key pair maintained in
the TLS PAKE adapter component.

The reason is that this would help integrating both OPAQUE and would also
allow for re-using the exact same same interface for FIDO2-based two-factor
authentication (password + TOKEN).

I.e. one might prepare the interface “===========” such that it is configurable
whether client and server shall or shall not activate the certificate-based authentication
component present in today’s TLS core implementations or not.


Yours,

Björn

**Comment by chris-wood** [comment]
As discussed, this isn't a software architecture document. It's a protocol specification, and I don't think this sort of information helps the reader or implementer in any way. I'm inclined to close this issue with no action.

**Comment by chris-wood** [comment]
Closing as resolved.
